# Voice, Texture, Augment, 3-task

n_epoch: 10 # 20 # 50
result_root: /data2/longshen/musecoco_data/results
out_dir: all_in_one_fl_dbaug_nohist
with_hist: False # False | full | drum | drum_and_range
reorder_tgt: False
do_augment: True
voice_control: True
texture_control: True

# Train and test
flatten_content: True
multi_task: True # For both train and test

# Test and Reinst
test_task: recon # recon | simp | elab
infer_exp_name: recon

# Reinst
midi_fp: /data2/longshen/musecoco_data/full_song/caihong/detokenized.mid
reinst_exp_name: ap_recon
replace_inst: ['i-0', 'txt-3'] # inst list | False
hist_autoregressive: False

pt_ckpt: /data2/longshen/musecoco_data/pretrained_models/200m/model
tokenizer_fp: /data2/longshen/musecoco_data/pretrained_models/200m/tokenizer_ft
data_root: /data2/longshen/musecoco_data/datasets
bs: 36
bs_test: 1
lr: 0.0001
warmup_steps: 0
weight_decay: 0.01

