# Voice, Texture, Augment, 3-task

n_epoch: 10 # 20 # 50
result_root: /data1/longshen/musecoco_data/results
out_dir: fl_dbaug_rangehist_only
with_hist: range # False | full | drum | drum_and_range | range
reorder_tgt: False
do_augment: True
aug_hist: False
voice_control: True
texture_control: True
remove_drum: False

# Train and test
flatten_content: True
multi_task: True # For both train and test

# Test and Reinst
test_task: recon # recon | simp | elab
infer_exp_name: recon

# Reinst
midi_fp: /data1/longshen/musecoco_data/full_song/caihong/detokenized.mid
reinst_exp_name: many_inst
# replace_inst: ['i-0', 'txt-3', 'i-26', 'txt-3', 'i-128'] # inst list | False
# replace_inst: ['i-40', 'txt-0', 'i-41', 'txt-0', 'i-42', 'txt-0']
replace_inst: ['i-0', 'txt-0', 'i-2', 'txt-2', 'i-26', 'txt-1', 'i-24', 'txt-3', 'i-33', 'txt-0', 'i-128']
hist_autoregressive: True

pt_ckpt: /data1/longshen/musecoco_data/pretrained_models/200m/model
tokenizer_fp: /data1/longshen/musecoco_data/pretrained_models/200m/tokenizer_ft
data_root: /data1/longshen/musecoco_data/datasets
bs: 36
bs_test: 1
lr: 0.0001
warmup_steps: 0
weight_decay: 0.01

