# Voice, Texture, Augment, 3-task
task: recon # arrange | recon 

n_epoch: 50 # 20 # 50
result_root: /data1/longshen/musecoco_data/results
out_dir: 20m_baseline_anneal_ep50
with_hist: full # False | full | drum | drum_and_range | drum_range_pos | range_pos
reorder_tgt: True
voice_control: True
texture_control: False
fast_dev_run: False
remove_drum: False

# Model
lit_model_class: LitMuseCoco

# Augmentation related
do_augment: True # deprecated, not used
aug_inst_slight: False
aug_drum: False
aug_bass: False
aug_hist: False
aug_inst: False
aug_content: False
aug_denoise: False

# Validation
n_gen_val_per_batch: 1

# Train and test
flatten_content: True
multi_task: True # For both train and test

# Infer
infer_exp_name: recon # recon | rand_inst
infer_with: mini_valid
infer_inp_fn: ${infer_with}.txt
infer_out_fn: out_${infer_with}_${infer_exp_name}.txt
eval_out_fn: eval_${infer_with}_${infer_exp_name}.txt

# Test and Reinst
test_task: recon # recon | simp | elab

# Reinst
midi_fp: /data1/longshen/musecoco_data/full_song/caihong/detokenized.mid
reinst_exp_name: caihong_jband_k50p1.0
# replace_inst: ['i-0'] # inst list | False
# replace_inst: ['i-40', 'txt-1', 'i-41', 'txt-1', 'i-42', 'txt-1']
# replace_inst: ['i-0', 'txt-0', 'i-2', 'txt-2', 'i-26', 'txt-1', 'i-24', 'txt-3', 'i-33', 'txt-0', 'i-128']
# replace_inst: ['i-0', 'i-2', 'i-26', 'i-24', 'i-33']
# replace_inst: ['i-40', 'i-41', 'i-42'] # string trio
replace_inst: ['i-64', 'i-40', 'i-61', 'i-26', 'i-0', 'i-44', 'i-33'] # jazz band
hist_autoregressive: True

pt_ckpt: /data1/longshen/musecoco_data/pretrained_models/20m/model
tokenizer_fp: /data1/longshen/musecoco_data/pretrained_models/20m/tokenizer_ft
data_root: /data1/longshen/musecoco_data/datasets
bs: 36
bs_test: 1
lr: 0.0001
warmup_steps: 0
weight_decay: 0.01

