# Voice, Texture, Augment, 3-task
task: arrange # arrange | recon 

n_epoch: 10 # 20 # 50
result_root: /data2/longshen/musecoco_data/results
out_dir: ar_hist
with_hist: full # False | full | drum | drum_and_range | drum_range_pos
reorder_tgt: False
voice_control: False
texture_control: False

# Augmentation related
do_augment: True
remove_drum: True

# Train and test
flatten_content: False
multi_task: False # For both train and test

# Test
infer_exp_name: recon

# Test and Reinst
test_task: recon # recon | simp | elab

# Reinst
midi_fp: /data2/longshen/musecoco_data/full_song/caihong/detokenized.mid
reinst_exp_name: str_trio
# replace_inst: ['i-0', 'txt-3'] # inst list | False
replace_inst: ['i-40', 'i-41', 'i-42']
hist_autoregressive: True

pt_ckpt: /data2/longshen/musecoco_data/pretrained_models/200m/model
tokenizer_fp: /data2/longshen/musecoco_data/pretrained_models/200m/tokenizer_ft
data_root: /data2/longshen/musecoco_data/datasets
bs: 36
bs_test: 1
lr: 0.0001
warmup_steps: 0
weight_decay: 0.01

