# Voice, Texture, Augment, 3-task
task: recon # arrange | recon 

n_epoch: 10 # 20 # 50
result_root: /data1/longshen/musecoco_data/results/arrangement/1b
out_dir: lora_lr1e-4_r8 # _r8
with_hist: range # False | full | drum | drum_and_range | drum_range_pos | range_pos
reorder_tgt: True
voice_control: True
texture_control: False
fast_dev_run: False
remove_drum: True

# Model
pt_ckpt: /data1/longshen/musecoco_data/pretrained_models/1b/model
tokenizer_fp: /data1/longshen/musecoco_data/pretrained_models/20m/tokenizer_ft
lit_model_class: LitMuseCocoLoRA

# Augmentation related
do_augment: True # deprecated, not used
aug_inst_slight: True
aug_drum: True
aug_bass: True
aug_hist: True
aug_inst: True
aug_content: True
aug_denoise: False

# Validation
n_gen_val_per_batch: 2

# Train and test
flatten_content: True
multi_task: True # For both train and test

# Infer
infer_exp_name: recon # recon | rand_inst
infer_with: mini_valid
infer_inp_fn: ${infer_with}.txt
infer_out_fn: out_${infer_with}_${infer_exp_name}.txt
eval_out_fn: eval_${infer_with}_${infer_exp_name}.txt

# Test and Reinst
test_task: recon # recon | simp | elab

# Reinst
midi_fp: /data1/longshen/musecoco_data/full_song/caihong/detokenized.mid
# midi_fp: /data1/longshen/musecoco_data/full_song/never/Never-Gonna-Give-You-Up-3_new.mid
reinst_exp_name: caihong_jazz
# replace_inst: ['i-0', 'txt-3'] # inst list | False
# replace_inst: ['i-40', 'txt-1', 'i-41', 'txt-1', 'i-42', 'txt-1']
# replace_inst: ['i-0', 'txt-0', 'i-2', 'txt-2', 'i-26', 'txt-1', 'i-24', 'txt-3', 'i-33', 'txt-0', 'i-128']
# replace_inst: ['i-0', 'i-2', 'i-26', 'i-24', 'i-33']
# replace_inst: ['i-40', 'i-41', 'i-42']
# replace_inst: ['i-0']
replace_inst: ['i-64', 'i-40', 'i-61', 'i-26', 'i-0', 'i-44', 'i-33'] # jazz band
hist_autoregressive: True


data_root: /data1/longshen/musecoco_data/datasets
bs: 8
bs_test: 1
lr: 0.0001
warmup_steps: 0
weight_decay: 0.0 # 0.01

