n_epoch: 10 # 20 # 50
result_root: /data2/longshen/Datasets/slakh2100_flac_redux/musecoco_results_hf
out_dir: baseline_nohist
with_hist: False # For both training and inference
reorder_tgt: False
do_augment: False
test_task: simp # recon | simp | elab
reinst_exp_name: ap_ag_recon
hist_autoregressive: False

replace_inst: ['i-0', 'i-24'] # inst list | False
midi_fp: /data2/longshen/musecoco_data/full_song/caihong/detokenized.mid

pt_ckpt: '/data2/longshen/Checkpoints/musecoco/transformers/200m/model'
tokenizer_fp: '/data2/longshen/Checkpoints/musecoco/transformers/200m/tokenizer_ft'
data_root: '/data2/longshen/Datasets/slakh2100_flac_redux/musecoco_data/slakh_segmented_2bar_sss'
bs: 36
bs_test: 1
lr: 0.0001
warmup_steps: 0
weight_decay: 0 #0.01
# fast_dev_run: False
