# Voice, Texture, Augment, 3-task

n_epoch: 10 # 20 # 50
result_root: /data1/longshen/musecoco_data/results
out_dir: fl_dbaug_rphist_drh
with_hist: drum_range_pos # False | full | drum | drum_and_range | drum_range_pos
reorder_tgt: False
do_augment: True
voice_control: True
texture_control: True
fast_dev_run: False

# Augmentation related
remove_drum: False

# Validation
n_gen_val_per_batch: 2

# Train and test
flatten_content: True
multi_task: True # For both train and test

# Test and Reinst
test_task: recon # recon | simp | elab
infer_exp_name: recon

# Reinst
midi_fp: /data1/longshen/musecoco_data/full_song/caihong/detokenized.mid
reinst_exp_name: str_trio
# replace_inst: ['i-0', 'txt-0', 'i-2', 'txt-2', 'i-26', 'txt-1', 'txt-2', 'i-33', 'txt-0', 'i-128'] # inst list | False
# replace_inst: ['i-44', 'txt-3']
replace_inst: ['i-40', 'txt-1', 'i-41', 'txt-1', 'i-42', 'txt-1']
hist_autoregressive: True

pt_ckpt: /data1/longshen/musecoco_data/pretrained_models/200m/model
tokenizer_fp: /data1/longshen/musecoco_data/pretrained_models/200m/tokenizer_ft
data_root: /data1/longshen/musecoco_data/datasets
bs: 36
bs_test: 1
lr: 0.0001
warmup_steps: 0
weight_decay: 0.01

